### ISSUE TITLE
LV-T80 "Robin" can't find the old T800 Textures

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/SXTContinued#63] opened 2018-11-08 19:38 UTC
[LOG 22:08:07.308] PartLoader: Compiling Part 'SXT/Parts/Rocketry/Engine/J2Engine/part/SXTLT80'
[ERR 22:08:07.309] PartCompiler: Cannot replace texture 'model004' as cannot find texture 'Squad/Parts/FuelTank/fuelTankT800/model000' to replace with

[ERR 22:08:07.310] PartCompiler: Cannot replace texture 'model005_NRM' as cannot find texture 'Squad/Parts/FuelTank/fuelTankT800/model001' to replace with

**Comment by linuxgurugamer** [comment] 2018-11-08 20:33
Would be nice to know what version of KSP you are using

**Comment by yalov** [comment] 2018-11-08 20:34
KSP 1.5.1

**Comment by linuxgurugamer** [comment] 2018-11-08 20:37
The textures don't exist in KSP anymore, I've asked for permission to include them in the mod.  Will have to wait and see

**Comment by yalov** [comment] 2018-11-08 21:08
they are used for a shroud, so maybe change to the new one?

![screenshot22](https://user-images.githubusercontent.com/12796450/48227485-8bdd7e00-e3b3-11e8-8604-dd85f3b5e2b5.png)

**Comment by yalov** [comment] 2018-11-08 21:43
Absence these models and textures look like a bug, because the old 1.25 fuel tank's configs are there, and they can't loads: 

[LOG 00:34:36.134] PartLoader: Compiling Part 'Squad/Parts/FuelTank/fuelTankT100/fuelTankT100/fuelTankSmallFlat'
[ERR 00:34:36.135] PartCompiler: Cannot clone model from 'Squad/Parts/FuelTank/fuelTankT100' directory as model does not exist
[ERR 00:34:36.161] PartCompiler: Cannot compile model
[ERR 00:34:36.161] PartCompiler: Cannot compile part

[LOG 00:34:36.162] PartLoader: Compiling Part 'Squad/Parts/FuelTank/fuelTankT200/fuelTankT200/fuelTankSmall'
[ERR 00:34:36.162] PartCompiler: Cannot clone model from 'Squad/Parts/FuelTank/fuelTankT200' directory as model does not exist
[ERR 00:34:36.163] PartCompiler: Cannot compile model
[ERR 00:34:36.164] PartCompiler: Cannot compile part

[LOG 00:34:36.164] PartLoader: Compiling Part 'Squad/Parts/FuelTank/fuelTankT400/fuelTankT400/fuelTank'
[ERR 00:34:36.165] PartCompiler: Cannot clone model from 'Squad/Parts/FuelTank/fuelTankT400' directory as model does not exist
[ERR 00:34:36.165] PartCompiler: Cannot compile model
[ERR 00:34:36.166] PartCompiler: Cannot compile part

[LOG 00:34:36.166] PartLoader: Compiling Part 'Squad/Parts/FuelTank/fuelTankT800/fuelTankT800/fuelTank_long'
[ERR 00:34:36.167] PartCompiler: Cannot clone model from 'Squad/Parts/FuelTank/fuelTankT800' directory as model does not exist
[ERR 00:34:36.168] PartCompiler: Cannot compile model
[ERR 00:34:36.169] PartCompiler: Cannot compile part

**Comment by linuxgurugamer** [comment] 2018-11-09 15:34
It's not a "bug", it's a "feature".
The files got renamed when they retextured them

**Comment by linuxgurugamer** [comment] 2018-11-09 15:35
> they are used for a shroud, so maybe change to the new one?
> 
> ![screenshot22](https://user-images.githubusercontent.com/12796450/48227485-8bdd7e00-e3b3-11e8-8604-dd85f3b5e2b5.png)

The problem is that the model references specific areas of the texture, there is virtually no chance that the new textures will have the images in the same location.

**Comment by linuxgurugamer** [comment] 2018-11-09 15:36
The old configs are there probably so that old vessels will still be loaded

**Comment by linuxgurugamer** [comment] 2018-11-09 17:45
I found the old textures, will be getting an update out later today

**Comment by Ruedii** [comment] 2018-11-10 00:40
Best option would be to link to the new textures if possible.  

However, this means remapping the texture layout which is a lot of work.

I'd recommend moving some other textures to new equivalents preemptively if they are easy to do so (e.g. "White Texture" objects.)  Squad appears to be slowly moving everything over to these new texture maps.

I wish I knew more about modeling.  I know what can be done and how, but I don't know how to do it myself in the sense that I don't have the skills to do so learned fully. 

Do you have source model files from the original author?  If so can you publish them to the GIT-Hub archive.  It would be ideal to use those, but simply unpacking the models for edit would also work, even if it's the inferior option.

**Comment by Ruedii** [comment] 2018-11-10 01:03
I did inadvertently find a way to find the original files on steam.  When you upgrade to the new version it keeps the old files around on those particular texture files.  

I was wondering if we could ask Squad to have a pack through the DLC interface on steam called "Legacy files for mods" which include all the legacy parts models, part files and textures.  The part files, are of course should listed as "hidden" legacy parts so they don't show up in the craft editor.

For those who get the game through other sites, it should be listed as a separate DLC download in the manner used for Making History in the appropriate site.  (GoG has a DLC download mechanism now, as does the Humble Store download if they use it.   For the web store they can add that.)

Update: only seems to get some of the files with the ones Steam doesn't delete.  The shroud still isn't fixed.

If it's just the shroud we should just go to the new shroud texture.  Replacing the shroud model is far easier than modifying the rest of the model.

**Comment by linuxgurugamer** [comment] 2018-11-10 02:43
The files are there, in a directory called:  Squad/zDeprecated
But the game ignores that directory, so I'll be including a script which will copy the missing texture files, I've also updated the parts to use the coped textures.
Planning on a sunday release

**Comment by linuxgurugamer** [comment] 2018-11-10 02:44
I don't have the original files

**Comment by Ruedii** [comment] 2018-11-11 10:57
OK, well in that case they can be derived from the packaged model files, and only some minor detail might be lost.  It  Might be a good enhancement task to switch out the model.  Definitely beyond the scope of this bug.

Maybe the KSP community needs to make a metaproject database of mods that have open enhancements and minor bugs.

Anyhow, I found more missing texture bugs.  Seems the pipes have them as well. I'm not sure if you found those yet, or not.

**Comment by linuxgurugamer** [comment] 2018-11-11 21:35
I've found all the missing texture bugs, will be fixed in the 1.5.1 release.
There will be a script needed to be run one time after install to copy the files over

**Comment by Ruedii** [comment] 2018-11-16 10:26
Is the script auto-run, or do users need to run it?

**Comment by linuxgurugamer** [comment] 2018-11-16 18:03
There is a script for Windows (.bat) and one for Linux/Unix (.sh).  Read the README for instructions.
No, it is not auto-run, can't be.

**Closed as completed by linuxgurugamer** 2018-11-16 18:03 UTC

**Comment by yalov** [comment] 2018-11-16 20:06
@hebaruSan can running the scripts be added to the ckan?

**Comment by yalov** [comment] 2018-11-16 20:22
or copying from GameData\Squad\zDeprecated\ to the modfolder in the .netkan "install" section

**Comment by HebaruSan** [comment] 2018-11-16 20:36
@yalov, there's a request for post-install scripts on file: KSP-CKAN/CKAN#1488

So far nobody has worked on it.
