### ISSUE TITLE
Take Command integration for SXT

### ISSUE THREAD

**Issue by TheKurgan** [linuxgurugamer/SXTContinued#13] opened 2016-12-21 15:48 UTC
Changing the Takecommand.cfg file to read (below) results in a kerbal spawning in the The EAS-316 "Meadowlark" Observation Pod seat as he should, but then gets ejected violently... most times dying.

Possibly because of clearance? The pod also has two seats, but only 1 can be assigned a crew member in the editor. 

@PART[*]:HAS[@MODULE[KerbalSeat]]:FOR[TakeCommand]
{
    CrewCapacity = 1
    MODULE
    {
        name = TakeCommand
        minimumCrew = 1
    }
}

**Comment by linuxgurugamer** [comment] 2016-12-25 13:33
the problem is related to the 2nd seat.

**Comment by linuxgurugamer** [comment] 2017-01-05 00:33
and has been fixed in Takecommand

**Closed as completed by linuxgurugamer** 2017-01-05 00:33 UTC
